import { MyColors } from "../utils/color";

export const defineBorder = () => ({
  GUID: "df54d2",
  Name: "Custom_Model",
  Transform: {
    posX: 0.0,
    posY: 1.62407672,
    posZ: 0.0,
    rotX: 0.0,
    rotY: 180.0,
    rotZ: 0.0,
    scaleX: 9.3,
    scaleY: 9.3,
    scaleZ: 9.3,
  },
  Nickname: "",
  Description: "",
  GMNotes: "",
  AltLookAngle: {
    x: 0,
    y: 0,
    z: 0,
  },
  ColorDiffuse: {
    ...MyColors.dark,
    a: 0,
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  CustomMesh: {
    MeshURL:
      "https://steamusercontent-a.akamaihd.net/ugc/2501267533360144140/FB01B1FCBB1BBBDD61EDC0845E6BE0DCF7515FD8/",
    DiffuseURL: "",
    NormalURL: "",
    ColliderURL:
      "https://steamusercontent-a.akamaihd.net/ugc/2501267533360144140/FB01B1FCBB1BBBDD61EDC0845E6BE0DCF7515FD8/",
    Convex: true,
    MaterialIndex: 3,
    TypeIndex: 0,
    CustomShader: {
      SpecularColor: {
        r: 0,
        g: 0,
        b: 0,
      },
      SpecularIntensity: 0,
      SpecularSharpness: 2,
      FresnelStrength: 0,
    },
    CastShadows: true,
  },
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: "",
});
