export const defineSietch = () => ({
  GUID: "d340bd",
  Name: "Custom_Model",
  Transform: {
    posX: 0.0,
    posY: 0.0,
    posZ: 0.0,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
  },
  Tags: ["coded", "decal"],
  Nickname: "",
  Description: "",
  GMNotes: "",
  AltLookAngle: {
    x: 0,
    y: 0,
    z: 0,
  },
  ColorDiffuse: {
    r: 1,
    g: 1,
    b: 1,
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  CustomMesh: {
    MeshURL:
      "https://steamusercontent-a.akamaihd.net/ugc/2501267533360131017/8E3DD120A3082277EF588A168F619B1C9AB122CB/",
    DiffuseURL: "",
    NormalURL: "",
    ColliderURL: "",
    Convex: true,
    MaterialIndex: 3,
    TypeIndex: 0,
    CustomShader: {
      SpecularColor: {
        r: 0,
        g: 0,
        b: 0,
      },
      SpecularIntensity: 0,
      SpecularSharpness: 2,
      FresnelStrength: 0,
    },
    CastShadows: true,
  },
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: "",
  ChildObjects: [
    {
      GUID: "8f559e",
      Name: "Custom_Model",
      Transform: {
        posX: 0.0,
        posY: 0.0,
        posZ: 0.0,
        rotX: 0.0,
        rotY: 0.0,
        rotZ: 0.0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
      },
      Nickname: "",
      Description: "",
      GMNotes: "",
      AltLookAngle: {
        x: 0,
        y: 0,
        z: 0,
      },
      ColorDiffuse: {
        r: 0,
        g: 0,
        b: 0,
      },
      LayoutGroupSortIndex: 0,
      Value: 0,
      Locked: true,
      Grid: true,
      Snap: true,
      IgnoreFoW: false,
      MeasureMovement: false,
      DragSelectable: true,
      Autoraise: true,
      Sticky: true,
      Tooltip: true,
      GridProjection: false,
      HideWhenFaceDown: false,
      Hands: false,
      CustomMesh: {
        MeshURL:
          "https://steamusercontent-a.akamaihd.net/ugc/2501267533360498907/24031B0876B60EE39CA382119D1F911880B0611B/",
        DiffuseURL: "",
        NormalURL: "",
        ColliderURL: "",
        Convex: true,
        MaterialIndex: 3,
        TypeIndex: 0,
        CustomShader: {
          SpecularColor: {
            r: 0,
            g: 0,
            b: 0,
          },
          SpecularIntensity: 0,
          SpecularSharpness: 2,
          FresnelStrength: 0,
        },
        CastShadows: true,
      },
      LuaScript: "",
      LuaScriptState: "",
      XmlUI: "",
    },
  ],
});

export const defineOrnithopter = () => ({
  GUID: "bb7a44",
  Name: "Custom_Model",
  Transform: {
    posX: 0.0,
    posY: 0.0,
    posZ: 0.0,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
  },
  Tags: ["coded", "decal"],
  Nickname: "",
  Description: "",
  GMNotes: "",
  AltLookAngle: {
    x: 0,
    y: 0,
    z: 0,
  },
  ColorDiffuse: {
    r: 1,
    g: 1,
    b: 1,
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  CustomMesh: {
    MeshURL:
      "https://steamusercontent-a.akamaihd.net/ugc/2501267533360129527/4A3607F4AEFE9F42E898DB90084E135EBDEDFC1D/",
    DiffuseURL: "",
    NormalURL: "",
    ColliderURL: "",
    Convex: true,
    MaterialIndex: 3,
    TypeIndex: 0,
    CustomShader: {
      SpecularColor: {
        r: 0,
        g: 0,
        b: 0,
      },
      SpecularIntensity: 0,
      SpecularSharpness: 2,
      FresnelStrength: 0,
    },
    CastShadows: true,
  },
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: "",
  ChildObjects: [
    {
      GUID: "84294e",
      Name: "Custom_Model",
      Transform: {
        posX: 0.0,
        posY: 0.0,
        posZ: 0.0,
        rotX: 0.0,
        rotY: 0.0,
        rotZ: 0.0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
      },
      Nickname: "",
      Description: "",
      GMNotes: "",
      AltLookAngle: {
        x: 0,
        y: 0,
        z: 0,
      },
      ColorDiffuse: {
        r: 0,
        g: 0,
        b: 0,
      },
      LayoutGroupSortIndex: 0,
      Value: 0,
      Locked: true,
      Grid: true,
      Snap: true,
      IgnoreFoW: false,
      MeasureMovement: false,
      DragSelectable: true,
      Autoraise: true,
      Sticky: true,
      Tooltip: true,
      GridProjection: false,
      HideWhenFaceDown: false,
      Hands: false,
      CustomMesh: {
        MeshURL:
          "https://steamusercontent-a.akamaihd.net/ugc/2501267533360480999/9E94B6F08F192BB5CAD44D939532AE136C359A87/",
        DiffuseURL: "",
        NormalURL: "",
        ColliderURL: "",
        Convex: true,
        MaterialIndex: 3,
        TypeIndex: 0,
        CustomShader: {
          SpecularColor: {
            r: 0,
            g: 0,
            b: 0,
          },
          SpecularIntensity: 0,
          SpecularSharpness: 2,
          FresnelStrength: 0,
        },
        CastShadows: true,
      },
      LuaScript: "",
      LuaScriptState: "",
      XmlUI: "",
    },
  ],
});

export const defineCity = () => ({
  GUID: "1fa096",
  Name: "Custom_Model",
  Transform: {
    posX: 0.0,
    posY: 0.0,
    posZ: 0.0,
    rotX: 0.0,
    rotY: 0.0,
    rotZ: 0.0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
  },
  Tags: ["coded", "decal"],
  Nickname: "",
  Description: "",
  GMNotes: "",
  AltLookAngle: {
    x: 0,
    y: 0,
    z: 0,
  },
  ColorDiffuse: {
    r: 1,
    g: 1,
    b: 1,
  },
  LayoutGroupSortIndex: 0,
  Value: 0,
  Locked: true,
  Grid: true,
  Snap: true,
  IgnoreFoW: false,
  MeasureMovement: false,
  DragSelectable: true,
  Autoraise: true,
  Sticky: true,
  Tooltip: true,
  GridProjection: false,
  HideWhenFaceDown: false,
  Hands: false,
  CustomMesh: {
    MeshURL:
      "https://steamusercontent-a.akamaihd.net/ugc/2501267533360125097/70796AF4B88A93573A5DCEAC35C3BDF236CC74AD/",
    DiffuseURL: "",
    NormalURL: "",
    ColliderURL: "",
    Convex: true,
    MaterialIndex: 3,
    TypeIndex: 0,
    CustomShader: {
      SpecularColor: {
        r: 0,
        g: 0,
        b: 0,
      },
      SpecularIntensity: 0,
      SpecularSharpness: 2,
      FresnelStrength: 0,
    },
    CastShadows: true,
  },
  LuaScript: "",
  LuaScriptState: "",
  XmlUI: "",
  ChildObjects: [
    {
      GUID: "b6c7d6",
      Name: "Custom_Model",
      Transform: {
        posX: 0.0,
        posY: 0.0,
        posZ: 0.0,
        rotX: 0.0,
        rotY: 0.0,
        rotZ: 0.0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
      },
      Nickname: "",
      Description: "",
      GMNotes: "",
      AltLookAngle: {
        x: 0,
        y: 0,
        z: 0,
      },
      ColorDiffuse: {
        r: 0,
        g: 0,
        b: 0,
      },
      LayoutGroupSortIndex: 0,
      Value: 0,
      Locked: true,
      Grid: true,
      Snap: true,
      IgnoreFoW: false,
      MeasureMovement: false,
      DragSelectable: true,
      Autoraise: true,
      Sticky: true,
      Tooltip: true,
      GridProjection: false,
      HideWhenFaceDown: false,
      Hands: false,
      CustomMesh: {
        MeshURL:
          "https://steamusercontent-a.akamaihd.net/ugc/2501267533360018189/2F86213BA45C8C37EF679F46DA2AD838C2648DB6/",
        DiffuseURL: "",
        NormalURL: "",
        ColliderURL: "",
        Convex: true,
        MaterialIndex: 3,
        TypeIndex: 0,
        CustomShader: {
          SpecularColor: {
            r: 0,
            g: 0,
            b: 0,
          },
          SpecularIntensity: 0,
          SpecularSharpness: 2,
          FresnelStrength: 0,
        },
        CastShadows: true,
      },
      LuaScript: "",
      LuaScriptState: "",
      XmlUI: "",
    },
  ],
});
